---
# tasks file for wordpress

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Install dependences
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-devel
    - mysql-devel

- name: Install mysql-python
  pip:
    name: MySQL-python

- name: Create dir wp
  file:
    path: /usr/share/nginx/blog
    state: directory
    owner: nginx
    group: nginx
    mode: 0755

- name: WORDPRESS | Download WordPress
  get_url:
    url=http://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress-latest.tar.gz

- name: WORDPRESS | Extract archive
  command: tar -vzxf wordpress-latest.tar.gz
  args:
    chdir: /tmp

- name: WORDPRESS | Move wordpress paste
  shell: mv /tmp/wordpress/* /usr/share/nginx/blog
  args:
    executable: /bin/bash

- name: WORDPRESS | Add group wordpress
  group:
    name: wordpress

- name: WORDPRESS | Add user wordpress
  user:
    name=wordpress
    group=wordpress
    home=/usr/share/nginx/blog

- name: WORDPRESS | Create WordPress database
  mysql_db:
    login_host: "{{ db_host }}"
    login_password: '{{ db_root_pw }}'
    login_port: '3306'
    login_user: '{{ db_root }}'
    name: "{{ wp_db_name }}"
    state: present

- name: WORDPRESS | Create WordPress database user
  mysql_user:
    login_host: "{{ db_host }}"
    login_password: '{{ db_root_pw }}'
    login_port: '3306'
    login_user: '{{ db_root }}'
    name: '{{ wp_db_user }}'
    password: "{{ wp_db_password }}"
    priv: '{{ wp_db_name }}.*:ALL'
    host: '%'
    state: present

- name: WORDPRESS | Copy WordPress config file
  template:
    src=wp-config.php
    dest=/usr/share/nginx/blog

- name: WORDPRESS | Change ownership of WordPress installation
  file:
    path=/usr/share/nginx
    owner=wordpress
    group=wordpress
    state=directory
    recurse=yes

- name: WORDPRESS | Start php-fpm
  service:
    name: php-fpm
    state: restarted
